kind: Service
apiVersion: v1
metadata:
  name: docker-spring-boot-service
spec:
  type: LoadBalancer  
  ports:
  - name: https
    port: 8080
    targetPort: 8080
  - name: http
    port: 8081
    targetPort: 8081
  selector:
    app: docker-spring-boot
